version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: on-failure
    hostname: gitlab.cortijodemazas.com
    ports:
    - "80:80"
    - "443:443"
