web:
  image: gitlab/gitlab-ee:latest
  container_name: gitlab
  restart: always
  hostname: gitlab.cortijodemazas.com
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab.cortijodemazas.com'
      gitlab_rails['gitlab_shell_ssh_port'] = 2224
  ports:
  - "8065:80"
  - "8066:443"
  - "2224:22"
