version: "3.3"
services:
  gitlab:
    image: gitlab/gitlab-ee:latest
    container_name: gitlab
    restart: always
    hostname: gitlab.cortijodemazas.com
    ports:
    - "8065:80"
    - "8066:443"
    - "22:22"
